app = "ahmiyat-blockchain"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 5001
  [[services.ports]]
    port = 5001
